clear code
IBobbyBrownI/KanbanBoard pull request #3
Opened 2023-12-08 14:05 UTC by IBobbyBrownI

i cleared my code!

2023-12-12 17:28 UTC, valentinHruzinski92 commented on script/script.js
>  	tasks = JSON.parse(data)
оберни парсинг в try/catch

2023-12-12 17:28 UTC, valentinHruzinski92 commented on script/script.js
> +button.onclick = function () {
назови кнопку более понятно. не сразу понятно что такое button

2023-12-12 17:28 UTC, valentinHruzinski92 commented on script/script.js
> +			taskObj.name = "Unnamed";
если имя неправильное, тогда мы не создаем таск. Делаешь просто return

2023-12-12 17:28 UTC, valentinHruzinski92 commented on script/script.js
> +		let data = localStorage.getItem('taskBlockList');
тебе не обязательно доставать таск с локалстореджа. У тебя же они записаны в  tasks

2023-12-12 17:28 UTC, valentinHruzinski92 commented on script/script.js
> +		let selectedTaskId = editedTask.id;
2 момента. 
1) в таких случаях не обязательно выносить в отдельную переменну. если просто с объекта поле достаешь
2) если ты не перезаписываешь переменную, сетай в const

2023-12-12 17:28 UTC, valentinHruzinski92 commented on script/script.js
>  		}
добавь блок else c alert. если не находишь объект - сообщение об ошибке и ретурн

2023-12-12 17:28 UTC, valentinHruzinski92 commented on script/script.js
> +		button.textContent = "Add"
вынеси в отдельную функцию switchMode. Она будет переключать между edit и add

2023-12-12 17:28 UTC, valentinHruzinski92 commented on script/script.js
> +		location.reload()
если ты перезагружешь, тебе нет смысла во многих действиях сверху. 
ты обновил локалсторедж. Сейчас тебе аналогично надо обновить массив tasks и обновить элемент сам

2023-12-12 17:28 UTC, valentinHruzinski92 commented on script/script.js
> +	deleteButton.addEventListener('click', function () {
пользователь может случайно нажать на кнопку. Тебе надо что бы пользователь подтвердил действие. используй функцию confirm

2023-12-12 17:28 UTC, valentinHruzinski92 commented on script/script.js
> +function cancelClick() {
как раз то что я писал выше. про switchMode. можно и 2 функциями сделать. но там где я отписал просто вызывай эту функцию. не дублируй код

2023-12-12 17:28 UTC, valentinHruzinski92 commented on script/script.js
> +	let cancelButton = document.getElementById('cancelButton');
и саму кнопку можно вынести вначало. что бы не искать ее каждый раз

2023-12-12 17:28 UTC, valentinHruzinski92 commented on script/script.js
> +		if (parentId === 'todo-lane-1') {
можно сделать что-то типа такого. достать последний символс айдишки парента и добавить единицу. Пример ниже. Вместо 4 условий

columnToInsert = document.querySelector('#todo-lane-' + (+parentId[parentId.length -1]+1));

if(!columnToInsert ) return;

2023-12-12 17:28 UTC, valentinHruzinski92 commented on script/script.js
> +		const parent = activeElement.parentElement;
parent определяешь, но не вижу где используешь

2023-12-12 17:29 UTC, valentinHruzinski92 requested changes
пингани меня когда все пофиксаешь

2023-12-13 11:59 UTC, IBobbyBrownI commented on script/script.js
> +		location.reload()
не совсем понял...

2023-12-13 12:02 UTC, IBobbyBrownI commented on script/script.js
> +button.onclick = function () {
сделано

2023-12-13 12:02 UTC, IBobbyBrownI commented on script/script.js
> +			taskObj.name = "Unnamed";
сделано

2023-12-13 12:03 UTC, IBobbyBrownI commented on script/script.js
> +		let selectedTaskId = editedTask.id;
сделано

2023-12-13 12:03 UTC, IBobbyBrownI commented on script/script.js
>  		}
сделано

2023-12-13 12:11 UTC, IBobbyBrownI commented on script/script.js
> +		let data = localStorage.getItem('taskBlockList');
сделано

2023-12-13 12:31 UTC, IBobbyBrownI commented on script/script.js
> +		location.reload()
сделано!

2023-12-13 12:34 UTC, IBobbyBrownI commented on script/script.js
> +	let cancelButton = document.getElementById('cancelButton');
сделано

2023-12-13 12:35 UTC, IBobbyBrownI commented on script/script.js
> +		const parent = activeElement.parentElement;
сделано

2023-12-13 12:37 UTC, IBobbyBrownI commented on script/script.js
> +		if (parentId === 'todo-lane-1') {
сделано

2023-12-13 12:46 UTC, IBobbyBrownI commented on script/script.js
> +	deleteButton.addEventListener('click', function () {
сделано

2023-12-13 12:47 UTC, IBobbyBrownI commented on script/script.js
> +		location.reload()
сделано

2023-12-13 12:49 UTC, IBobbyBrownI commented on script/script.js
> +	let cancelButton = document.getElementById('cancelButton');
сделано

2023-12-13 12:49 UTC, IBobbyBrownI commented on script/script.js
> +		if (parentId === 'todo-lane-1') {
сделано

2023-12-13 12:49 UTC, IBobbyBrownI commented on script/script.js
> +		const parent = activeElement.parentElement;
сделано

2023-12-14 07:01 UTC, IBobbyBrownI commented on script/script.js
>  	tasks = JSON.parse(data)
сделано

2023-12-27 12:20 UTC, closed without merging